name: Notify
on:
  workflow_call:
    inputs:
      id:
        description: Posted in the first step for use in finding the run ID later
        type: string
      body:
        description: Posted in the GitHub step summary
        type: string
      failure:
        description: Should this be marked as a failure?
        type: boolean
        default: false

jobs:
  id:
    name: Workflow ID
    runs-on: ubuntu-latest
    steps:
      - name: ${{ inputs.id }}
        run: echo run identifier ${{ inputs.id }}
      
      - name: Job summary
        run: | 
          echo '### Job Summary' >> $GITHUB_STEP_SUMMARY
          echo '${{ inputs.body }}' >> $GITHUB_STEP_SUMMARY

      - name: Trigger failure
        if: inputs.failure
        run: |
          exit 1